ez/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('upload/', views.ask_for_repo, {'view':'upload'}, name='ask_for_repo_up'),
    path('download/', views.ask_for_repo, {'view':'download'}, name='ask_for_repo_up'),
    path('upload/<str:name>/', views.upload, name='upload'),
    path('ajax/upload_files/', views.upload_files, name='upload_files'),
    path('upload_complete/', views.upload_complete, name='upload_complete'),
    path('download/<str:name>/', views.download, name='download'),
    path('ajax/download_files/', views.download_files, name='download_files'),
]

ez2share/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from django.conf import settings

urlpatterns = [
    path('', include('ez.urls')),
    path('admin/', admin.site.urls)
]

handler404 = 'ez.views.error_404_view'

ez/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
import os

class Repository(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return settings.UPLOAD_DIR+'{0}/{1}'.format(instance.repository.owner.username, filename)

class Files(models.Model):
    repository = models.ForeignKey(Repository, on_delete=models.CASCADE)
    file = models.FileField(upload_to=user_directory_path)
    username = models.CharField(max_length=100, default="unknown")
    created_at = models.DateTimeField(auto_now_add=True)

    @property
    def filename(self):
        return os.path.basename(self.file.name)

ez/forms.py
from django import forms

class PasswordForm(forms.Form):
    repository_password = forms.CharField(label='Password', max_length=100)

class FileFieldForm(forms.Form):
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

class RepoForm(forms.Form):
    repository_name = forms.CharField(label='Repository Name', max_length=100)

ez/views.py
from django.shortcuts import render
from django.http import Http404, JsonResponse, HttpResponse, HttpResponseRedirect
from django.core.exceptions import PermissionDenied
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .models import Repository, Files
from .forms import PasswordForm, RepoForm, FileFieldForm
from django.views.generic.edit import FormView
from django import forms
import time
import os
import zipfile
from io import BytesIO
import pprint

def error_404_view(request, exception):
    return render(request,'errors/404.html', {})

def upload(request, name):
    # raise 404 if repo does not exist
    try:
        Repository.objects.get(owner__username=name)
    except Repository.DoesNotExist:
        raise Http404("Repository does not exist.")
    context = {}
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PasswordForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            password = form['repository_password'].value()
            user = authenticate(username=name, password=password)
            if user is not None:
                login(request, user)
                form = FileFieldForm()
                return render(request, 'ez/upload.html', {'form': form})
            else:
                context['form'] = PasswordForm()
                context['error_message'] = 'Password incorrect.'

    # if a GET (or any other method) we'll create a blank form
    else:
        context['form'] = PasswordForm()
    context['name'] = name
    context['view'] = 'upload'
    return render(request, 'ez/ask_for_connection.html', context)

def upload_files(request):
    user = request.user
    if not user.is_authenticated:
        raise PermissionDenied
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        username = request.POST.get('username')
        files = request.FILES.getlist('files[]')
        repository = Repository.objects.get(owner=user)
        for file in files:
            f = Files(repository=repository, file=file, username=username)
            f.save()
        return JsonResponse({'success': True})
    # if a GET (or any other method) we'll create a blank form
    else:
        raise PermissionDenied

def ask_for_repo(request, view='upload'):
    context = {}
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RepoForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            repo_name = form['repository_name'].value()
            try:
                Repository.objects.get(owner__username=repo_name)
                return HttpResponseRedirect(repo_name)
            except Repository.DoesNotExist:
                context['error_message'] = 'Repository does not exist.'

    # if a GET (or any other method) we'll create a blank form
    context['form'] = RepoForm()
    context['view'] = view
    return render(request, 'ez/ask_for_repo.html', context)

def upload_complete(request):
    return render(request, 'ez/upload_complete.html', {})

def download(request, name):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PasswordForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            password = form['repository_password'].value()
            user = authenticate(username=name, password=password)
            if user is not None:
                login(request, user)
                repository = Repository.objects.get(owner=user)
                raw_files = Files.objects.filter(repository=repository)
                files = []
                for file in raw_files:
                    files.append((file.id, file.filename, file.created_at, file.username))
                return render(request, 'ez/download.html', {'files': files})
            else:
                raise PermissionDenied

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PasswordForm()
    return render(request,
                  'ez/ask_for_connection.html',
                  {'name': name, 'view': 'download', 'form': form})

def download_files(request):
    user = request.user
    if not user.is_authenticated:
        return HttpResponseRedirect('/download/')
    else:
        logout(request)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        download_ids = request.POST.getlist('download')

        stream = BytesIO()
        temp_zip_file = zipfile.ZipFile(stream, mode='w')
        for id in download_ids:
            file = Files.objects.get(pk=id)
            path = str(file.file)
            name = file.filename
            temp_zip_file.write(path, arcname=name)
        temp_zip_file.close()
        response = HttpResponse(stream.getvalue(), content_type='application/zip')
        response['Content-Disposition'] = 'attachment; filename="'+user.username+'.zip"'
        return response
    # if a GET (or any other method) we'll create a blank form
    else:
        return HttpResponseRedirect('/download/')

ez/templates/ez/ask_for_connection.html
{% extends "ez/base.html" %}
{% load static %}
{% block content %}
<style>
  #login-container {
    height: 100vh;
    width: 100vw;
    margin: 0;
    padding: 0;
  }

  #form{
    margin: 0 auto;
  }

  #title{
    font-family: 'Geo', sans-serif;
    font-weight: normal;
    font-size: 38px;
    padding-bottom: 2pt;
    border-bottom: solid 1px grey;
    width: 100%;
  }

  #sub-title{
    font-family: 'Open sans', sans-serif;
    font-weight: normal;
    font-size: 20px;
    margin-bottom: 15pt;
  }

  #id_repository_password{
    width: 100%;
  }

  #submit-button{
    float: right;
    margin-top: 5pt;
  }

</style>

<div id="login-container" class="row center-xs middle-xs">
  <div class="col-xs-9 col-sm-7 col-md-5 col-lg-3">
    <div class="row start-xs">
      <div class="col-xs-12">
        <div class="box">
          <div id="title"><span>Ez 2 Share</span></div>
          <div id="sub-title">Login for <span class="text-magenta">{{name}}</span></div>

          <form id="form" action="/{{view}}/{{name}}/" method="post">
            {% csrf_token %}
            <input type="password" id="id_repository_password" name="repository_password" placeholder="Password">
            <input id="submit-button" type="submit" value="Connect">
          </form>

          {% if error_message %}
            <small class="text-alert">{{error_message}}</small>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

ez/templates/ez/ask_for_repo.html
{% extends "ez/base.html" %}
{% load static %}
{% block content %}
<style>
  #login-container {
    height: 100vh;
    width: 100vw;
    margin: 0;
    padding: 0;
  }

  #form{
    margin: 0 auto;
  }

  #title{
    font-family: 'Geo', sans-serif;
    font-weight: normal;
    font-size: 38px;
    padding-bottom: 2pt;
    border-bottom: solid 1px grey;
    width: 100%;
  }

  #sub-title{
    font-family: 'Open sans', sans-serif;
    font-weight: normal;
    font-size: 20px;
    margin-bottom: 15pt;
  }

  #id_repository_name{
    width: 100%;
  }

  #submit-button{
    float: right;
    margin-top: 5pt;
  }

</style>

<div id="login-container" class="row center-xs middle-xs">
  <div class="col-xs-9 col-sm-7 col-md-5 col-lg-3">
    <div class="row start-xs">
      <div class="col-xs-12">
        <div class="box">
          <div id="title"><span>Ez 2 Share</span></div>
          <div id="sub-title">Go to <span class="text-magenta">:</span></div>

          <form id="form" action="/{{view}}/" method="post">
            {% csrf_token %}
            <input type="text" id="id_repository_name" name="repository_name" placeholder="Repository name">
            <input id="submit-button" type="submit" value="Connect">
          </form>

          {% if error_message %}
            <small class="text-alert">{{error_message}}</small>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

ez/templates/ez/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>ez2share</title>
    <script src='{% static "ez/js/jquery-3.3.1.min.js" %}'></script>
    <link rel="stylesheet" href='{% static "ez/css/flexboxgrid.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "ez/css/fonts.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "ez/css/table.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "ez/css/base.css" %}' type="text/css">
</head>

<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

ez/templates/ez/download.html
{% extends "ez/base.html" %}
{% load static %}
{% block content %}

<style>
  #upload-container {
    height: 100vh;
    width: 100vw;
    margin: 0;
    padding: 0;
  }

  #form{
    margin: 0 auto;
  }

  #title{
    font-family: 'Geo', sans-serif;
    font-weight: normal;
    font-size: 38px;
    padding-bottom: 2pt;
    border-bottom: solid 1px grey;
    width: 100%;
    margin-top: 30px;
  }

  #sub-title{
    font-family: 'Open sans', sans-serif;
    font-weight: normal;
    font-size: 20px;
    margin-bottom: 15pt;
  }

  #submit-button{
    float: right;
    margin-top: 5pt;
  }

  img{
    width: 36px;
    opacity: 0.3;
  }

  .item-div{
    position: relative;
    border: solid 1px grey;
    margin: 2px;
    padding: 1px;
    border-radius: 5px;
    display: inline-block;
    -webkit-transition: border-color 0.25s ease-in-out, color 0.25s ease-in-out;
    transition: border-color 0.25s ease-in-out, color 0.25s ease-in-out;
  }

  .item-div > input{
    margin: 0;
    display: none;
  }

  .item-div img{
    margin-left: 10px;
    vertical-align: bottom;
  }

  .item-div:hover{
    box-shadow: 0px 0px 5px grey;
  }

  .selected{
    box-shadow: 0px 0px 5px grey;
  }

  .hide{
    display: none;
  }

  .menu-button{
    position: relative;
    border: solid 1px grey;
    margin: 2px;
    padding: 1px;
    border-radius: 5px;
    display: inline-block;
    -webkit-transition: border-color 0.25s ease-in-out;
    transition: border-color 0.25s ease-in-out;
    height: 30px;
    padding-left: 5px;
    padding-right: 5px;
  }

  .menu-button:hover{
    box-shadow: 0px 0px 5px grey;
  }

  .select-all::before{ content:"Select all"; }

  .deselect-all::before{ content:"Deselect all"; }

  #search-input{
    border: solid 1px grey;
    margin: 2px;
    padding: 1px;
    border-radius: 5px;
    display: inline-block;
    padding-left: 5px;
    padding-right: 5px;
  }

</style>

<div id="upload-container" class="row center-xs">
  <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
    <div class="row start-xs">
      <div class="col-xs-12">
        <div class="box">
          <div id="title"><span>Ez 2 Share</span></div>
            <input id="search-input" type="text" placeholder="Search" value=""></input>
            <form id="form" action="/ajax/download_files/" method="post">
              {% csrf_token %}
              <table>
                <thead>
                  <tr>
                    <th>File</th>
                    <th>Uploader Name</th>
                    <th>Deposit date</th>
                    <th class="align-right"><input type="checkbox" id="select-all" onclick="_selectAll()"></input></th>
                  </tr>
                </thead>
                <tbody>
                  {% for id, name, created_at, username in files %}
                    <tr class="item-tr" data-name="{{name}}" data-user="{{username}}">
                      <td>{{name}}</td>
                      <td>{{username}}</td>
                      <td>{{created_at}}</td>
                      <td class="align-right"><input type="checkbox" name="download" value={{id}}></input></td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            <input id="submit-button" type="submit" value="Download">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script>

  function _selectAll(){
    let isOn = $('#select-all').is(':checked');
    if(isOn){
      $('.item-tr:not(.hide)').find('input').prop('checked', true);
    }
    else{
      $('.item-tr:not(.hide)').find('input').prop('checked', false);
    }
  }

  function _filterItems(filter){
    var filter = filter;
    $('.item-tr').removeClass('hide');
    $('.item-tr').filter(function( index ) {
      return $(this).data('name').indexOf(filter) === -1 && $(this).data('user').indexOf(filter) === -1;
    }).addClass('hide');
  }

  $( document ).ready(function() {

      $('#search-input').on('keyup', function(){
        var value = $(this).val();
        _filterItems(value);
      });

      $('#search-input').on('change', function(){
        var value = $(this).val();
        _filterItems(value);
      });
  });
</script>
{% endblock %}

ez/templates/ez/upload.html
{% extends "ez/base.html" %}
{% load static %}
{% block content %}

<script src="https://transloadit.edgly.net/releases/uppy/v1.0.0/uppy.min.js"></script>
<link href="https://transloadit.edgly.net/releases/uppy/v1.0.0/uppy.min.css" rel="stylesheet">
<style>
  #upload-container {
    height: 100vh;
    width: 100vw;
    margin: 0;
    padding: 0;
  }

  #form{
    margin: 0 auto;
  }

  #title{
    font-family: 'Geo', sans-serif;
    font-weight: normal;
    font-size: 38px;
    padding-bottom: 2pt;
    border-bottom: solid 1px grey;
    width: 100%;
  }

  #sub-title{
    font-family: 'Open sans', sans-serif;
    font-weight: normal;
    font-size: 20px;
    margin-bottom: 15pt;
  }

  #id_repository_name{
    width: 100%;
  }

</style>

<div id="upload-container" class="row center-xs middle-xs">
  <div class="col-xs-8">
    <div class="row start-xs">
      <div class="col-xs-12">
        <div id="title"><span>Ez 2 Share</span></div>
        <input id="username" value="" placeholder="your name, optional."></input>
        <div id="drop-zone"></div>
      </div>
    </div>
  </div>
</div>

<script>
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
  }
  var csrftoken = getCookie('csrftoken');

  var uppy = Uppy.Core()
  uppy.use(Uppy.Dashboard, {
    trigger: '.UppyModalOpenerBtn',
    inline: true,
    target: '#drop-zone',
    replaceTargetContent: true,
    showProgressDetails: true,
    note: 'Images only.',
    height: 470,
    width: "100%",
    restrictions: {
      maxFileSize: 20000000,
      allowedFileTypes: ['image/*', '.jpg', '.jpeg', '.png', '.gif']
    },
    browserBackButtonClose: true
  })

  uppy.use(Uppy.XHRUpload, {
    endpoint: '/ajax/upload_files/',
    headers: {
      'X-CSRFToken': csrftoken
    },
    metaFields: ['username'],
  })

  uppy.on('file-added', (file) => {
    uppy.setFileMeta(file.id, {
      username: $('#username').val()
    })
  })
</script>
{% endblock %}

ez/templates/ez/upload_complete.html
{% extends "ez/base.html" %}
{% block content %}

<div style="height: 100vh; width: 100vw" class="row center-xs middle-xs">
  <span class="text-magenta">Upload Complete !</span>
</div>
{% endblock %}